version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  robotHandler:
    class: robot.output.pyloggingconf.RobotHandler
loggers:
# Console logging
  DatabaseApi:
    level: INFO
    handlers: [console, robotHandler]
    propagate: no
root:
  level: WARN
  handlers: [console]
