application_name: helix2-test
filesystem:
  config: external/config
  features: external/features
  reports: external/reports
  fixtures: external/fixtures
external_config_file: external/.test_conf.yaml